#include "driver_proxy.h"

#include <cstring>

JSValue createOpenDriverFunction(JSContext* ctx, JSValueConst driverCtor) {
    static const char kFactorySource[] =
        "(function(DriverCtor){\n"
        "  function normalizeOptions(options) {\n"
        "    if (options == null) return { metaTimeoutMs: 5000 };\n"
        "    if (typeof options !== 'object' || Array.isArray(options)) {\n"
        "      throw new TypeError('openDriver: options must be an object');\n"
        "    }\n"
        "    const allowed = new Set(['metaTimeoutMs']);\n"
        "    for (const k of Object.keys(options)) {\n"
        "      if (!allowed.has(k)) {\n"
        "        throw new TypeError('openDriver: unknown option: ' + k);\n"
        "      }\n"
        "    }\n"
        "    let metaTimeoutMs = 5000;\n"
        "    if (options.metaTimeoutMs !== undefined) {\n"
        "      if (typeof options.metaTimeoutMs !== 'number') {\n"
        "        throw new TypeError('openDriver: metaTimeoutMs must be a number');\n"
        "      }\n"
        "      if (!Number.isFinite(options.metaTimeoutMs) || options.metaTimeoutMs <= 0 ||\n"
        "          !Number.isInteger(options.metaTimeoutMs)) {\n"
        "        throw new RangeError('openDriver: metaTimeoutMs must be a positive integer');\n"
        "      }\n"
        "      metaTimeoutMs = options.metaTimeoutMs;\n"
        "    }\n"
        "    return { metaTimeoutMs };\n"
        "  }\n"
        "\n"
        "  function normalizeCommandOptions(options) {\n"
        "    if (options == null) return { timeoutMs: 0 };\n"
        "    if (typeof options !== 'object' || Array.isArray(options)) {\n"
        "      throw new TypeError('driver command options must be an object');\n"
        "    }\n"
        "    const allowed = new Set(['timeoutMs']);\n"
        "    for (const k of Object.keys(options)) {\n"
        "      if (!allowed.has(k)) {\n"
        "        throw new TypeError('unknown driver command option: ' + k);\n"
        "      }\n"
        "    }\n"
        "    const timeoutMs = options.timeoutMs ?? 0;\n"
        "    if (!Number.isInteger(timeoutMs) || timeoutMs < 0) {\n"
        "      throw new RangeError('timeoutMs must be a non-negative integer');\n"
        "    }\n"
        "    return { timeoutMs };\n"
        "  }\n"
        "\n"
        "  function terminalError(task, cmd) {\n"
        "    const err = new Error(task.errorText || ('driver exited during command: ' + cmd));\n"
        "    err.code = task.exitCode;\n"
        "    return err;\n"
        "  }\n"
        "\n"
        "  function resolveTerminalMessage(target, cmd, task, msg, timeoutMs) {\n"
        "      if (!msg) {\n"
        "        if (task.done) {\n"
        "          throw terminalError(task, cmd);\n"
        "        }\n"
        "        if (timeoutMs > 0) {\n"
        "          target.terminate();\n"
        "          const err = new Error('Command timeout: ' + cmd + ' (' + timeoutMs + 'ms)');\n"
        "          err.code = 'ETIMEDOUT';\n"
        "          throw err;\n"
        "        }\n"
        "        throw new Error('Command ended without terminal response: ' + cmd);\n"
        "      }\n"
        "\n"
        "      if (msg.status === 'event') {\n"
        "        return null;\n"
        "      }\n"
        "      if (msg.status === 'error') {\n"
        "        const data = (msg.data && typeof msg.data === 'object') ? msg.data : {};\n"
        "        const err = new Error(data.message || ('Command failed: ' + cmd));\n"
        "        err.code = msg.code;\n"
        "        err.data = msg.data;\n"
        "        throw err;\n"
        "      }\n"
        "      if (msg.status === 'done') {\n"
        "        return msg.data;\n"
        "      }\n"
        "\n"
        "      target.terminate();\n"
        "      throw new Error('Unexpected task status: ' + msg.status);\n"
        "  }\n"
        "\n"
        "  async function waitTaskToTerminal(target, cmd, task, timeoutMs) {\n"
        "    if (timeoutMs <= 0) {\n"
        "      const msg = await globalThis.__scheduleTask(task);\n"
        "      return resolveTerminalMessage(target, cmd, task, msg, 0);\n"
        "    }\n"
        "\n"
        "    const deadline = Date.now() + timeoutMs;\n"
        "    while (true) {\n"
        "      const remaining = Math.max(0, deadline - Date.now());\n"
        "      const result = await globalThis.__waitAny([task], remaining);\n"
        "      const value = resolveTerminalMessage(target, cmd, task, result ? result.msg : null, timeoutMs);\n"
        "      if (value !== null) {\n"
        "        return value;\n"
        "      }\n"
        "    }\n"
        "  }\n"
        "\n"
        "  function buildStartArgs(args) {\n"
        "    if (args !== undefined && args !== null && !Array.isArray(args)) {\n"
        "      throw new TypeError('openDriver: args must be an array');\n"
        "    }\n"
        "    const src = Array.isArray(args) ? args : [];\n"
        "    for (const a of src) {\n"
        "      if (typeof a !== 'string') throw new TypeError('openDriver: args item must be string');\n"
        "    }\n"
        "    const filtered = src.filter(a => !a.startsWith('--profile='));\n"
        "    filtered.push('--profile=keepalive');\n"
        "    return filtered;\n"
        "  }\n"
        "\n"
        "  return async function openDriver(program, args, options) {\n"
        "    if (typeof program !== 'string' || program.length === 0) {\n"
        "      throw new TypeError('openDriver: program must be a non-empty string');\n"
        "    }\n"
        "    const opts = normalizeOptions(options);\n"
        "    const startArgs = buildStartArgs(args);\n"
        "    const driver = new DriverCtor();\n"
        "    if (!driver.start(program, startArgs)) {\n"
        "      throw new Error('Failed to start driver: ' + program);\n"
        "    }\n"
        "    const meta = driver.queryMeta(opts.metaTimeoutMs);\n"
        "    if (!meta) {\n"
        "      driver.terminate();\n"
        "      throw new Error('Failed to query metadata from: ' + program +\n"
        "        ' (timeoutMs=' + opts.metaTimeoutMs + ')');\n"
        "    }\n"
        "    const commands = new Set((meta.commands || []).map(c => c.name));\n"
        "    let busy = false;\n"
        "    return new Proxy(driver, {\n"
        "      get(target, prop) {\n"
        "        if (prop === '$driver') return target;\n"
        "        if (prop === '$meta') return meta;\n"
        "        if (prop === '$rawRequest') return (cmd, data) => target.request(cmd, data || {});\n"
        "        if (prop === '$close') return () => target.terminate();\n"
        "        if (typeof prop === 'string' && commands.has(prop)) {\n"
        "          return (params = {}, options) => {\n"
        "            if (busy) {\n"
        "              throw new Error('DriverBusyError: request already in flight');\n"
        "            }\n"
        "            const cmdOptions = normalizeCommandOptions(options);\n"
        "            busy = true;\n"
        "            try {\n"
        "              const task = target.request(prop, params);\n"
        "              return waitTaskToTerminal(target, prop, task, cmdOptions.timeoutMs)\n"
        "                .finally(() => {\n"
        "                  busy = false;\n"
        "                });\n"
        "            } catch (e) {\n"
        "              busy = false;\n"
        "              throw e;\n"
        "            }\n"
        "          };\n"
        "        }\n"
        "        return undefined;\n"
        "      }\n"
        "    });\n"
        "  };\n"
        "})";

    JSValue factory = JS_Eval(ctx, kFactorySource, std::strlen(kFactorySource),
                              "<stdiolink/open_driver_factory>", JS_EVAL_TYPE_GLOBAL);
    if (JS_IsException(factory)) {
        return factory;
    }

    JSValue args[1] = {driverCtor};
    JSValue openDriver = JS_Call(ctx, factory, JS_UNDEFINED, 1, args);
    JS_FreeValue(ctx, factory);
    return openDriver;
}
