// stdiolink single header
// Generated by pack_single_header.py

#pragma once

// console
#include "stdiolink/console/console_args.h"
#include "stdiolink/console/console_responder.h"
#include "stdiolink/console/system_options.h"

// doc
#include "stdiolink/doc/doc_generator.h"

// driver
#include "stdiolink/driver/driver_core.h"
#include "stdiolink/driver/help_generator.h"
#include "stdiolink/driver/icommand_handler.h"
#include "stdiolink/driver/iresponder.h"
#include "stdiolink/driver/log_redirector.h"
#include "stdiolink/driver/meta_builder.h"
#include "stdiolink/driver/meta_command_handler.h"
#include "stdiolink/driver/meta_exporter.h"
#include "stdiolink/driver/mock_responder.h"
#include "stdiolink/driver/stdio_responder.h"

// host
#include "stdiolink/host/config_injector.h"
#include "stdiolink/host/driver.h"
#include "stdiolink/host/driver_registry.h"
#include "stdiolink/host/form_generator.h"
#include "stdiolink/host/meta_cache.h"
#include "stdiolink/host/meta_version_checker.h"
#include "stdiolink/host/task.h"
#include "stdiolink/host/task_state.h"
#include "stdiolink/host/wait_any.h"

// protocol
#include "stdiolink/protocol/jsonl_parser.h"
#include "stdiolink/protocol/jsonl_serializer.h"
#include "stdiolink/protocol/jsonl_types.h"
#include "stdiolink/protocol/meta_schema_validator.h"
#include "stdiolink/protocol/meta_types.h"
#include "stdiolink/protocol/meta_validator.h"

#include "stdiolink/stdiolink_export.h"
