set(STDIOLINK_WINDOWS_APP_ICON_RC "${CMAKE_SOURCE_DIR}/cmake/windows/stdiolink_app_icon.rc")
set(STDIOLINK_WINDOWS_APP_ICON_FILE "${CMAKE_SOURCE_DIR}/cmake/windows/stdiolink.ico")

function(stdiolink_target_should_use_windows_icon out_var target_name)
    if(NOT TARGET ${target_name})
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    if(target_name STREQUAL "stdiolink_server" OR target_name STREQUAL "stdiolink_service")
        set(${out_var} TRUE PARENT_SCOPE)
        return()
    endif()

    get_target_property(_output_name ${target_name} OUTPUT_NAME)
    if(NOT _output_name)
        set(_output_name "${target_name}")
    endif()
    if(NOT _output_name MATCHES "^stdio\\.drv\\.")
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    get_target_property(_source_dir ${target_name} SOURCE_DIR)
    file(TO_CMAKE_PATH "${_source_dir}" _source_dir)
    if(_source_dir MATCHES "/src/demo(/|$)")
        set(${out_var} FALSE PARENT_SCOPE)
        return()
    endif()

    set(${out_var} TRUE PARENT_SCOPE)
endfunction()

function(stdiolink_apply_windows_app_icon target_name)
    if(NOT WIN32 OR NOT TARGET ${target_name})
        return()
    endif()

    if(NOT EXISTS "${STDIOLINK_WINDOWS_APP_ICON_RC}")
        message(FATAL_ERROR "Missing Windows app icon resource script: ${STDIOLINK_WINDOWS_APP_ICON_RC}")
    endif()
    if(NOT EXISTS "${STDIOLINK_WINDOWS_APP_ICON_FILE}")
        message(FATAL_ERROR "Missing Windows app icon file: ${STDIOLINK_WINDOWS_APP_ICON_FILE}")
    endif()

    get_target_property(_already_applied ${target_name} STDIOLINK_WINDOWS_APP_ICON_APPLIED)
    if(_already_applied)
        return()
    endif()

    file(TO_CMAKE_PATH "${STDIOLINK_WINDOWS_APP_ICON_FILE}" _icon_resource_path)
    target_sources(${target_name} PRIVATE "${STDIOLINK_WINDOWS_APP_ICON_RC}")
    target_compile_definitions(${target_name} PRIVATE STDIOLINK_APP_ICON_PATH="${_icon_resource_path}")
    set_property(TARGET ${target_name} PROPERTY STDIOLINK_WINDOWS_APP_ICON_APPLIED TRUE)
endfunction()

function(stdiolink_apply_windows_app_icon_to_registered_targets)
    if(NOT WIN32)
        return()
    endif()

    get_property(_all_exe_targets GLOBAL PROPERTY STDIOLINK_EXECUTABLE_TARGETS)
    foreach(_target IN LISTS _all_exe_targets)
        stdiolink_target_should_use_windows_icon(_should_apply "${_target}")
        if(_should_apply)
            stdiolink_apply_windows_app_icon("${_target}")
        endif()
    endforeach()
endfunction()
